########################################################################
# Formality Verification Script generated by:
#     fm_mk_script -o formality_auto.tcl "../synth/reports/default.svf"
# Formality (R)  Version X-2025.06-SP3 -- Oct 13, 2025
# Copyright 2007-2026 Synopsys, Inc. All rights reserved.
########################################################################

########################################################################
# Synopsys Auto Setup Mode
########################################################################

set synopsys_auto_setup true

# Note - The Synopsys Auto Setup mode is less conservative than the
# Formality default mode, and is more likely to result in a successful
# verification out-of-the-box.
#
# Setting synopsys_auto_setup will change the values of the variables
# listed here below.  You may change any of these variables back to
# their default settings to be more conservative.  Uncomment the
# appropriate lines below to revert back to their default settings:

      # set hdlin_ignore_parallel_case true
      # set hdlin_ignore_full_case true
      # set verification_verify_directly_undriven_output true
      # set hdlin_ignore_embedded_configuration false
      # set svf_ignore_unqualified_fsm_information true

########################################################################
# Specify number of processes on the local machine to use in parallel
# Default is 1 core
########################################################################

#set_host_options -max_cores 4

########################################################################
# Distributed Processing
#
# Uncomment the following line to enable distributed processing.
# Modify the arguments to the command to match your compute farm.
# See "man set_dpx_options" for details.
########################################################################

# set_dpx_options \
    -protocol <PROTOCOL> \
    -submit_command <COMMAND> \
    -max_workers <NUMBER> \
    -max_cores <NUMBER>     

########################################################################
# Setup for instantiated or function-inferred DesignWare components
########################################################################

set hdlin_dwroot /Tools/synopsys/syn/X-2025.06-SP2

########################################################################
# Search path
########################################################################

set search_path " \
	/home/ubajara.filho/Documentos/litting/Machine/. \
	/Tools/synopsys/syn/X-2025.06-SP2/libraries/syn \
	/Tools/synopsys/syn/X-2025.06-SP2/dw/syn_ver \
	/Tools/synopsys/syn/X-2025.06-SP2/dw/sim_ver \
	/home/ubajara.filho/Documentos/litting/Machine/libs "

########################################################################
# Read in the SVF file(s)
########################################################################

set_svf ../synth/reports/default.svf

########################################################################
# Read in the libraries
########################################################################

read_db -technology_library /home/ubajara.filho/Documentos/litting/Machine/libs/saed32rvt_tt1p05v25c.db


########################################################################
########################################################################

# set link_library " * dw_foundation.sldb saed32rvt_tt1p05v25c.db "

########################################################################
# Read in the Reference Design as verilog/vhdl source code
########################################################################

# No guide_environment analyze commands found in SVF

# USER INTERVENTION REQUIRED HERE:
# set_top vending_top


########################################################################
# Read in the Implementation Design created from DC
#
# Choose the file that you wish to verify
########################################################################

# USER INTERVENTION REQUIRED HERE:
# read_verilog -i /home/ubajara.filho/Documentos/litting/Machine/synth/vending_top_netlist.v
# read_ddc -i /home/ubajara.filho/Documentos/litting/Machine/synth/vending_top_netlist.ddc
# USER INTERVENTION REQUIRED HERE:
# set_top vending_top

########################################################################
# Verify and Report
#
# If the verification is not successful, the session will be saved and reports
# will be generated to help debug the failed or inconclusive verification.
########################################################################

if { ![verify] } {
  set DESIGN_NAME                   "vending_top"  ;#  The name of the top-level design
  set FMRM_FAILING_SESSION_NAME     ${DESIGN_NAME}
  set FMRM_FAILING_POINTS_REPORT    ${DESIGN_NAME}.fmv_failing_points.rpt
  set FMRM_ABORTED_POINTS_REPORT    ${DESIGN_NAME}.fmv_aborted_points.rpt

  set REPORTS_DIR "reports"

  file mkdir ${REPORTS_DIR}

  save_session -replace ${REPORTS_DIR}/${FMRM_FAILING_SESSION_NAME}
  report_failing_points > ${REPORTS_DIR}/${FMRM_FAILING_POINTS_REPORT}
  report_aborted > ${REPORTS_DIR}/${FMRM_ABORTED_POINTS_REPORT}
}
